name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'New tag name'
        required: true


jobs:
  
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git tag ${{ github.event.inputs.tag }}

  package:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: create artifact tar
        run: |
          tar -cvzf unlocodes.tar.gz vocab/ 

      - name: upload build details
        uses: actions/upload-artifact@v2
        with:
          name: unlocodes_artifact
          path: unlocodes.tar.gz

  release_tag:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs:
      - package
    runs-on: ubuntu-latest

    steps:
      - name: Get wrapper
        uses: actions/download-artifact@v2
        with:
          name: unlocodes_artifact
          path: ./

      - name: extract artifact
        run: |
          tar -zxvf unlocodes.tar.gz

      - name: Create Releases
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: 'vocab/*.jsonld'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: uncefact/vocabulary-outputs
          event-type: update-unlocodes